name: videopoly
version: 0.1.3
author: Groboclown <matt@groboclown.net>
description: Polymer custom element for embedding different video players into your Dart project.
homepage: https://github.com/groboclown/videopoly.dart
environment:
  sdk: 1.6.0
documentation: https://github.com/groboclown/videopoly.dart/tree/stable
dependencies:
  polymer: '>=0.15.0 <1.0.0'
  videoplay: '>=0.2.1 <1.0.0'
transformers:
- polymer:
    entry_points:
    - example/video-player/index.html
